### ISSUE TITLE
请问我该如何训练两个pose的任务？

### ISSUE THREAD

**Issue by YYJ6666** [JiayuanWang-JW/YOLOv8-multi-task#110]
我想要添加两个pose的检测头，然后做一个包含两个关键点任务的multitask，请问该如何修改我的配置文件？以及是否有其他位置需要修改？
另外：
我的数据集配置如下
```
labels_list:
  - test1
  - labels_face

tnc: 2  # number of classes
nc_list: [1,1]
map: [{'0':'0'},{'1':'1'}]

# Classes for all tasks
names:
  0: baby
  1: face
```
其中test1中有17个目标点 labels_face中有68个目标点
非常感谢！
