### ISSUE TITLE
多任务之中检测任务，指标不增长，始终为0

### ISSUE THREAD

**Issue by Lacacy** [JiayuanWang-JW/YOLOv8-multi-task#5]
参照readme进行的配置；请大佬帮忙看下这个问题吧

```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
#path: /data/jiayuan/BDDcoco/yolo_v8_toy  # dataset root dir
path: /data/wkx/develop/data/new_lawn  # dataset root dir

# Train/val/test image paths for all tasks
train: images/train  # train images for object detection (relative to 'path')


val: images/val  # val images for object detection (relative to 'path')


test: images/val  # test images for object detection (relative to 'path')

labels_list:
  - detection_object
  - seg_grass
  - seg_bush

tnc: 5  # number of classes
nc_list: [3,1,1]
map: [None,{'3':'0'},{'4':'0'}]

# Classes for all tasks
names:
  0: leaf
  1: branch
  2: bottle
  3: grass  # Add drivable class for drivable segmentation
  4: brush  # Add lane class for lane segmentation
```
